### ISSUE TITLE
ModuleNotFoundError: No module named 'miio'

### ISSUE THREAD

**Issue by michael-m52** [roth-m/mqttmiot-airpurifier3#4]
Hi, this is mostly my problem but was wondering if you could help

I had your script working perfectly but I have been playing about with all my miio utilities after having permission issues. I have now managed to break the your script and get this error:

ModuleNotFoundError: No module named 'miio'

Please remind me, is this based on "aholstenson/miio" or "rytilahti/python-miio"?

If "aholstenson/miio", then what is the installation syntax?

I tried all of these 

npm install miio
npm install -g miio 
sudo npm install miio
sudo npm install -g miio 

Thanks again for writing this useful script

**Comment by roth-m** [comment]
It's based on Python (rytilahti/python-miio).
